### ISSUE TITLE
Array parameters encoding fails

### ISSUE THREAD

**Issue by atvictor** [reactiverse/reactive-pg-client#160]
Version: 0.10.1

This query fails:
`pool.preparedQuery("select $1", Tuple.of(new Integer[] { 1, 2, 3, 4 }), System.out::println);`
with this exception:
`java.lang.ClassCastException: java.base/[Ljava.lang.Integer; cannot be cast to java.base/java.lang.String`

Reading the message formats (https://www.postgresql.org/docs/10/static/protocol-message-formats.html), I see we can send the parameters data types.

And this project seems to have handle that in the past, because now it's commented out: https://github.com/reactiverse/reactive-pg-client/blob/master/src/main/java/io/reactiverse/pgclient/impl/codec/encoder/MessageEncoder.java#L225

Maybe it's not the source of the issue? But it seems related.

**Comment by vietj** [comment]
can you try `Tuple.tuple((Object)new Integer[]{...})` ?

**Comment by atvictor** [comment]
I've tried with all the variants below:

`pool.preparedQuery("select $1", Tuple.tuple().addValue(new Integer[] { 1, 2, 3, 4 }), System.out::println);`

`pool.preparedQuery("select $1", Tuple.tuple().addIntegerArray(new Integer[] { 1, 2, 3, 4 }), System.out::println);`

None of them works.

Always with the same error:
`java.lang.ClassCastException: java.base/[Ljava.lang.Integer; cannot be cast to java.base/java.lang.String`

**Comment by vietj** [comment]
@atvictor can you try with the latest snapshot ? tuple validation was missing in some case (like the `preparedQuery` method

**Comment by vietj** [comment]
fixed by https://github.com/reactiverse/reactive-pg-client/issues/166

**Comment by atvictor** [comment]
I'm still having some trouble while dealing with in-list and `Tuple.of(new Integer[] {1, 2, 3, 4})` with:
- `select 1 where 1 in ($1)` throws `Values [[Ljava.lang.Integer;@2234ef05] cannot be coerced to [Integer]`
- `select 1 where 1 in ($1::int[])` throws `operator does not exist: integer = integer[]`

ATM, to circumvent this problem, I generate dynamic SQL with as many parameters as in-list members.

**Comment by vietj** [comment]
can you write a reproducing test for the first issue ?

**Comment by atvictor** [comment]
There it is: https://github.com/atvictor/reactive-pg-client/commit/4b9e2ae204f2c26e77eaaaab1215c18cf3353bb8

The first one works.
The second one fails.
The third one fails but was working in 0.10.1.
